main: space.aurillium.discordchat.Main
name: DiscordChat
version: 1.18.0
author: Aurillium (Memphis Marshall)
api-version: 1.18
commands:
    masterchatoff:
        description: Switches off the Discord chat.
        usage: /masterchatoff
        permission: DiscordChat.masterchatoff
        permission-message: You cannot use this command.
    masterchaton:
        description: Switches on the Discord chat.
        usage: /masterchaton
        permission: DiscordChat.masterchaton
        permission-message: You cannot use this command.
    chat:
        description: Switch the Discord chat on or off
        usage: /chat on|off
        permission: DiscordChat.chat
        permission-message: You cannot use this command.
